[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = ["Nicolas <nicolas.chaulet@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.17"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
